repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: requirements-txt-fixer

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: forbid-tabs
      - id: remove-tabs
        name: Replace tabs with white spaces for Python files
        files: \.(py)$
      - id: remove-tabs
        name: Replace tabs with white spaces for non-Python files
        files: ^.*\.(?!py$)[^.]+$
        args: ["--whitespaces-count", "2"]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=140

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args:
          - --line-length=140
        language_version: python3.9

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort Python imports
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        entry: autoflake
        language: python
        "types": [python]
        require_serial: true
        args:
          - --in-place
          - --ignore-init-module-imports
          - --remove-all-unused-imports
