FROM python:3.9-slim

COPY requirements.txt .

RUN pip install -U pip wheel \
  && pip install -r requirements.txt


WORKDIR /code
COPY web_backend.py .

ENV FLASK_APP web_backend
CMD ["flask", "run", "--host=0.0.0.0"]
