FROM python:3.9-slim

RUN apt-get update \
  && apt-get install -y postgresql-client \
  && rm -rf /var/lib/apt/lists/*

COPY web/requirements.txt .

RUN pip install -U pip wheel \
  && pip install -r requirements.txt

WORKDIR /web

ENV FLASK_APP application
CMD ["flask", "run", "--host=0.0.0.0"]
