version: "3.9"

services:
  web_backend:
    build:
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      CONFIG_ENV: dev-docker.yml
    networks:
      - frontend
      - backend
  client:
    build:
      dockerfile: Dockerfile.client_dev
    ports:
      - "3000:3000"
    networks:
      - frontend
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  frontend:
