version: "3.9"

services:
  web_backend:
    build:
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
  client:
    build:
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
