version: "3.8"

services:
  web_backend:
    build:
      context: ./
      dockerfile: Dockerfile.web_dev
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      CONFIG_ENV: dev-docker.yml
    volumes:
      - ./web:/web
    networks:
      - frontend
      - backend
  client:
    build:
      context: ./
      dockerfile: Dockerfile.client_dev
    ports:
      - "3000:3000"
    networks:
      - frontend
    volumes:
      - ./client:/client
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web_dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  frontend:
