FROM node:16.14-slim AS build_stage

WORKDIR /code/client

# Reason why we use npm ci
# https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci
COPY ./client/package.json .
COPY ./client/package-lock.json .
RUN npm ci

COPY ./client .

RUN npm run build:prod

FROM nginx:1.21.6-alpine

COPY --from=build_stage /code/client/build /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
