FROM python:3.9-slim

COPY web/requirements.txt .

RUN pip install -U pip wheel \
  && pip install -r requirements.txt

WORKDIR /code
COPY web .

ENV FLASK_APP web
CMD ["flask", "run", "--host=0.0.0.0"]
