FROM python:3.9-slim

RUN apt-get update \
  && apt-get install -y postgresql-client \
  && apt-get install -y build-essential python-dev \
  && rm -rf /var/lib/apt/lists/*

COPY web/requirements.txt .

RUN pip install -U pip wheel \
  && pip install -r requirements.txt

WORKDIR /web

ENV FLASK_APP application
CMD ["bash", "-c", "flask db upgrade && flask run --host=0.0.0.0"]
