apiVersion: apps/v1
kind: Deployment
metadata:
 name: client-prod
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: client-prod
 template:
   metadata:
     labels:
       app: client-prod
   spec:
     containers:
       - name: client-prod
         image: us-central1-docker.pkg.dev/yield-optimizer/yield-optimizer/client:latest
         resources:
           limits:
             cpu: "1"
             memory: "512Mi"
           requests:
             cpu: "1"
             memory: "512Mi"
         ports:
           - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-prod
spec:
  ports:
    - port: 80
    targetPort: 80
  selector:
    app: client-prod
  type: LoadBalancer
