apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-prod
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: client-prod
  template:
    metadata:
      labels:
        app: client-prod
    spec:
      containers:
        - name: client-prod
          image: registry.cloud.okteto.net/zhoujc999/yield-optimizer-client:latest
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-prod
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: client-prod
  type: LoadBalancer
