apiVersion: apps/v1
kind: Deployment
metadata:
 name: web-prod
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: web-prod
 template:
   metadata:
     labels:
       app: web-prod
   spec:
     containers:
       - name: web-prod
         image: us-central1-docker.pkg.dev/yield-optimizer/yield-optimizer/web:latest
         resources:
           limits:
             cpu: "1"
             memory: "2Gi"
           requests:
             cpu: "1"
             memory: "2Gi"
         ports:
           - containerPort: 5000
         env:
           - name: FLASK_ENV
             value: production
           - name: CONFIG_ENV
             value: prod.yml
---
apiVersion: v1
kind: Service
metadata:
  name: web-prod
spec:
  ports:
    - port: 5000
  selector:
    app: web-prod
