apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/zhoujc999/yield-optimizer/docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web-backend
  name: web-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /home/zhoujc999/yield-optimizer/docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.network/frontend: "true"
        io.kompose.service: web-backend
    spec:
      containers:
        - env:
            - name: CONFIG_ENV
              value: dev-docker.yml
            - name: FLASK_ENV
              value: development
          image: web-backend
          name: web_backend
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /web
              name: web-backend-claim0
      restartPolicy: Always
      volumes:
        - name: web-backend-claim0
          persistentVolumeClaim:
            claimName: web-backend-claim0
status: {}
