"""Add apy series data and pool name data

Revision ID: 0d93b9beb34e
Revises:
Create Date: 2022-02-27 03:05:21.321008

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0d93b9beb34e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pool_info",
        sa.Column("pool_name", sa.String(length=50), nullable=False),
        sa.Column("tokens", postgresql.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("pool_name"),
    )
    op.create_table(
        "apy_series_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("pool_info_name", sa.String(), nullable=False),
        sa.Column("pool_yield", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pool_info_name"],
            ["pool_info.pool_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("apy_series_data")
    op.drop_table("pool_info")
    # ### end Alembic commands ###
