"""Add pool_list

Revision ID: 48b4c65890d5
Revises: aa15c27a847b
Create Date: 2022-03-02 10:10:53.685000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "48b4c65890d5"
down_revision = "aa15c27a847b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pool_list",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("list_name", sa.String(length=50), nullable=False),
        sa.Column("pool_name", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["pool_name"],
            ["pool_info.pool_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pool_list")
    # ### end Alembic commands ###
