"""Add cascading delete for pool info

Revision ID: 86f7691a08ca
Revises: b03b5f5fb4a4
Create Date: 2022-03-06 10:46:49.078512

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "86f7691a08ca"
down_revision = "b03b5f5fb4a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("apy_series_data_pool_info_name_fkey", "apy_series_data", type_="foreignkey")
    op.create_foreign_key(
        "apy_series_data_pool_info_name_fkey_cascade",
        "apy_series_data",
        "pool_info",
        ["pool_info_name"],
        ["pool_name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("apy_series_data_pool_info_name_fkey_cascade", "apy_series_data", type_="foreignkey")
    op.create_foreign_key("apy_series_data_pool_info_name_fkey", "apy_series_data", "pool_info", ["pool_info_name"], ["pool_name"])
    # ### end Alembic commands ###
