"""Add cascade deletion

Revision ID: 976a602bde0b
Revises: b03b5f5fb4a4
Create Date: 2022-03-07 04:37:40.020545

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "976a602bde0b"
down_revision = "b03b5f5fb4a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("apy_series_data_pool_info_name_fkey", "apy_series_data", type_="foreignkey")
    op.create_foreign_key(
        "apy_series_data_pool_info_name_fkey_cascade", "apy_series_data", "pool_info", ["pool_info_name"], ["pool_name"], ondelete="CASCADE"
    )
    op.drop_constraint("list_pool_association_list_name_fkey", "list_pool_association", type_="foreignkey")
    op.drop_constraint("list_pool_association_pool_info_name_fkey", "list_pool_association", type_="foreignkey")
    op.create_foreign_key(
        "list_pool_association_list_name_fkey_cascade",
        "list_pool_association",
        "named_pool_list",
        ["list_name"],
        ["list_name"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "list_pool_association_pool_info_name_fkey_cascade",
        "list_pool_association",
        "pool_info",
        ["pool_info_name"],
        ["pool_name"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("list_pool_association_pool_info_name_fkey_cascade", "list_pool_association", type_="foreignkey")
    op.drop_constraint("list_pool_association_list_name_fkey_cascade", "list_pool_association", type_="foreignkey")
    op.create_foreign_key(
        "list_pool_association_pool_info_name_fkey", "list_pool_association", "pool_info", ["pool_info_name"], ["pool_name"]
    )
    op.create_foreign_key("list_pool_association_list_name_fkey", "list_pool_association", "named_pool_list", ["list_name"], ["list_name"])
    op.drop_constraint("apy_series_data_pool_info_name_fkey_cascade", "apy_series_data", type_="foreignkey")
    op.create_foreign_key("apy_series_data_pool_info_name_fkey", "apy_series_data", "pool_info", ["pool_info_name"], ["pool_name"])
    # ### end Alembic commands ###
