"""Create many-to-many ORM models of named list

Revision ID: b03b5f5fb4a4
Revises: 48b4c65890d5
Create Date: 2022-03-05 20:10:18.077536

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b03b5f5fb4a4"
down_revision = "48b4c65890d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("named_pool_list", sa.Column("list_name", sa.String(length=50), nullable=False), sa.PrimaryKeyConstraint("list_name"))
    op.create_table(
        "list_pool_association",
        sa.Column("pool_info_name", sa.String(length=50), nullable=False),
        sa.Column("list_name", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_name"],
            ["named_pool_list.list_name"],
        ),
        sa.ForeignKeyConstraint(
            ["pool_info_name"],
            ["pool_info.pool_name"],
        ),
        sa.PrimaryKeyConstraint("pool_info_name", "list_name"),
    )
    op.drop_table("pool_list")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pool_list",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("list_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("pool_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["pool_name"], ["pool_info.pool_name"], name="pool_list_pool_name_fkey"),
        sa.PrimaryKeyConstraint("id", name="pool_list_pkey"),
    )
    op.drop_table("list_pool_association")
    op.drop_table("named_pool_list")
    # ### end Alembic commands ###
