"""Add timezone to apy_series_data

Revision ID: f396850db0b4
Revises: 976a602bde0b
Create Date: 2022-03-07 05:05:37.095013

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f396850db0b4"
down_revision = "976a602bde0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("apy_series_data", "created_at", existing_type=sa.DateTime(), type_=postgresql.TIMESTAMP(timezone=True), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("apy_series_data", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), type_=sa.DateTime(), nullable=True)
    # ### end Alembic commands ###
