sqlalchemy:
  # Recommended to switch off for performance gain
  track_modifications: False

apy_api_worker:
  fetch_interval_seconds: 1
  insert_interval_seconds: 10

yield_endpoint:
  beefy: "https://api.beefy.finance/apy"
